### ISSUE TITLE
Can't compile swift LSP

### ISSUE THREAD

**Issue by K4stor** [NSHipster/articles#550]
Hello 

I am trying to use VS Code as main IDE as described in your article.
But when I run ```npm run createDevPackage``` it fails. Here is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'createDevPackage' ]
2 info using npm@6.4.1
3 info using node@v8.11.1
4 verbose run-script [ 'precreateDevPackage',
4 verbose run-script   'createDevPackage',
4 verbose run-script   'postcreateDevPackage' ]
5 info lifecycle sourcekit-lsp@0.0.1~precreateDevPackage: sourcekit-lsp@0.0.1
6 info lifecycle sourcekit-lsp@0.0.1~createDevPackage: sourcekit-lsp@0.0.1
7 verbose lifecycle sourcekit-lsp@0.0.1~createDevPackage: unsafe-perm in lifecycle true
8 verbose lifecycle sourcekit-lsp@0.0.1~createDevPackage: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Carsten/Development/sourcekit-lsp/Editors/vscode/node_modules/.bin:/Users/Carsten/.local/bin/luna-studio:/Developer/NVIDIA/CUDA-7.0/bin:/usr/local/texlive/2017/bin/x86_64-darwin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle sourcekit-lsp@0.0.1~createDevPackage: CWD: /Users/Carsten/Development/sourcekit-lsp/Editors/vscode
10 silly lifecycle sourcekit-lsp@0.0.1~createDevPackage: Args: [ '-c',
10 silly lifecycle   'npm install && ./node_modules/.bin/vsce package -o ./out/sourcekit-lsp-vscode-dev.vsix' ]
11 silly lifecycle sourcekit-lsp@0.0.1~createDevPackage: Returned: code: 1  signal: null
12 info lifecycle sourcekit-lsp@0.0.1~createDevPackage: Failed to exec createDevPackage script
13 verbose stack Error: sourcekit-lsp@0.0.1 createDevPackage: `npm install && ./node_modules/.bin/vsce package -o ./out/sourcekit-lsp-vscode-dev.vsix`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid sourcekit-lsp@0.0.1
15 verbose cwd /Users/Carsten/Development/sourcekit-lsp/Editors/vscode
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "createDevPackage"
18 verbose node v8.11.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error sourcekit-lsp@0.0.1 createDevPackage: `npm install && ./node_modules/.bin/vsce package -o ./out/sourcekit-lsp-vscode-dev.vsix`
22 error Exit status 1
23 error Failed at the sourcekit-lsp@0.0.1 createDevPackage script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

any hints ?

**Comment by mattt** [comment]
Hi @K4stor. I'm sorry you're having trouble compiling the sourcekit-lsp VSCode extension. Unfortunately, I can't really help with this. Please try opening an issue with the [sourcekit-lsp](https://github.com/apple/sourcekit-lsp) repository.

**Comment by K4stor** [comment]
Hi @mattt I found the solution myself 😄 

```
npm install event-stream
```

**Comment by mattt** [comment]
@K4stor No kidding! I didn't realize that project had that dependency. As it were, `event-stream` was recently compromised; you can read more about that here: https://gist.github.com/dominictarr/9fd9c1024c94592bc7268d36b8d83b3a. You might want to check your machine to ensure it hasn't installed an affected version.

**Comment by mattt** [comment]
After reading up on the incident (https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident), it appears that the compromised version of event-stream is a targeted attack against a bitcoin app, and shouldn't pose any risk outside that specific context:

> The event-stream package is widely used, but the malicious code targeted developers at a company that had a very specific development environment setup: running the payload in any other environment has no effect. This specific targeting means that, ultimately, most developers would not be affected even if they had mistakenly installed the malicious module.
